### PR TITLE
Olevegard/prototype

### PR DESCRIPTION
**Pull request by ole-vegard**
Initial prototype for CodedUI selenium tests for @magnarn to have a look at

### CODE REVIEW

**Comment by ole-vegard** [comment]
Note : These changes are just preliminary and a lot of it will  probably be changed later on

**Comment by NickAb** [comment]
Looks interesting. Ping me if you need anything or when it is ready for review.

**Comment by ole-vegard** [comment]
@NickAb Seems I pushed this to the wrong repo. It was meant for others to have a look at internally. But I will probably make a pull request on this later with most of these changes and some others later : )

**Comment by NickAb** [comment]
Cool. looking forward to hear from you.

**Pull request closed without merging**
